/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      // 1. RANGLAR (ReadingStyles.js dan olindi)
      colors: {
        'ielts-blue': '#2563eb',       // Asosiy ko'k
        'ielts-bg': '#f3f4f6',         // Orqa fon kulrang
        'text-primary': '#000000',     // Asosiy matn
        'text-secondary': '#374151',   // Ikkinchi darajali matn
        'border-color': '#e5e7eb',     // Chiziqlar rangi
        'highlight-yellow': '#fef08a', // Sariq highlight
        'highlight-green': '#86efac',  // Yashil (Evidence uchun)
        "secondary-fixed-dim": "#a3c9ff",
        "outline-variant": "#c1c6d5",
        "error-container": "#ffdad6",
        "on-tertiary": "#ffffff",
        "error": "#ba1a1a",
        "pure-white": "#ffffff",
        "ink-muted-48": "#7a7a7a",
        "pure-black": "#000000",
        "tile-dark-3": "#252527",
        "primary-container": "#0066cc",
        "on-secondary-fixed-variant": "#004882",
        "on-background": "#191c22",
        "tertiary-fixed-dim": "#ffb692",
        "outline": "#727784",
        "secondary-fixed": "#d3e3ff",
        "on-primary-fixed-variant": "#00458e",
        "action-blue": "#0066cc",
        "on-surface": "#191c22",
        "secondary": "#0060aa",
        "pearl": "#fafafc",
        "on-secondary-fixed": "#001c39",
        "primary-fixed-dim": "#aac7ff",
        "surface-container-highest": "#e1e2eb",
        "on-tertiary-container": "#ffe3d6",
        "secondary-container": "#2696fe",
        "ink-muted-80": "#333333",
        "body-muted": "#cccccc",
        "divider-soft": "rgba(0, 0, 0, 0.04)",
        "primary-fixed": "#d7e3ff",
        "surface-bright": "#f9f9ff",
        "on-error-container": "#93000a",
        "on-error": "#ffffff",
        "hairline": "#e0e0e0",
        "tertiary": "#883700",
        "chip-translucent": "rgba(210, 210, 215, 0.64)",
        "surface-dim": "#d8d9e2",
        "on-secondary": "#ffffff",
        "inverse-on-surface": "#eff0f9",
        "tertiary-fixed": "#ffdbcb",
        "sky-link-blue": "#2997ff",
        "tertiary-container": "#af4900",
        "surface": "#f9f9ff",
        "surface-container-low": "#f2f3fc",
        "on-surface-variant": "#414753",
        "inverse-surface": "#2e3037",
        "on-secondary-container": "#002d55",
        "focus-blue": "#0071e3",
        "primary": "#004e9f",
        "background": "#f9f9ff",
        "on-tertiary-fixed-variant": "#793000",
        "on-primary-container": "#dfe8ff",
        "inverse-primary": "#aac7ff",
        "surface-tint": "#005cba",
        "ink": "#1d1d1f",
        "parchment": "#f5f5f7",
        "surface-container-high": "#e6e8f1",
        "on-primary-fixed": "#001b3e",
        "on-primary": "#ffffff",
        "surface-variant": "#e1e2eb",
        "surface-container-lowest": "#ffffff",
        "on-tertiary-fixed": "#341100",
        "tile-dark-1": "#272729",
        "tile-dark-2": "#2a2a2c",
        "surface-container": "#ecedf6",
        warm: {
          canvas: '#faf9f5', surface: '#f5f0e8', card: '#efe9de', 'card-strong': '#e8e0d2',
          dark: '#181715', 'dark-elevated': '#252320', 'dark-soft': '#1f1e1b',
          ink: '#141413', body: '#3d3d3a', 'body-strong': '#252523',
          muted: '#6c6a64', 'muted-soft': '#8e8b82',
          hairline: '#e6dfd8', 'hairline-soft': '#ebe6df',
          primary: '#cc785c', 'primary-active': '#a9583e', 'primary-soft': '#e6dfd8',
          'on-primary': '#ffffff', 'on-dark': '#faf9f5', 'on-dark-soft': '#a09d96',
          success: '#5db872', warning: '#d4a017', error: '#c64545',
          'accent-teal': '#5db8a6', 'accent-amber': '#e8a55a',
        },
        vetra: {
          bg: '#FFFFFF',
          card: '#FFFFFF',
          border: '#E4E2E3',
          orange: '#F44A22',
          orangeGlow: '#FF6B47',
          text: '#161616',
          textMuted: '#A8AAAC',
          silver: '#FEF8E8',
          grey: '#E4E2E3',
          midnight: '#161616',
          stone: '#A8AAAC',
          blue: '#2563eb',
        }
      },
      // 2. SHRIFT (Default fontni Inter qilamiz)
      fontFamily: {
        sans: ['Outfit', 'Inter', 'system-ui', 'sans-serif'],
        display: ['Abel', 'sans-serif'],
        'serif-display': ['"Cormorant Garamond"', '"EB Garamond"', 'Georgia', 'serif'],
      },
      letterSpacing: {
        tightest: '-.075em',
        tighter: '-.05em',
        tight: '-.025em',
        normal: '0',
        wide: '.025em',
        wider: '.05em',
        widest: '.1em',
        'super-tight': '-0.02em',
      },
      lineHeight: {
        'extra-loose': '2.5',
        'premium': '1.15',
      },
      // 3. O'LCHAMLAR (Agar kerak bo'lsa)
      spacing: {
        'md': '16px',
        'xxs': '4px',
        'xs': '8px',
        'sm': '12px',
        'section': '96px',
        'xxl': '48px',
        'lg': '24px',
        'xl': '32px',
        'footer': '50px',
      },
      fontSize: {
        "body": ["17px", {"lineHeight": "1.47", "letterSpacing": "-0.01em", "fontWeight": "400"}],
        "body-strong": ["17px", {"lineHeight": "1.24", "letterSpacing": "-0.01em", "fontWeight": "600"}],
        "lead": ["28px", {"lineHeight": "1.14", "letterSpacing": "0.196px", "fontWeight": "400"}],
        "nav-link": ["12px", {"lineHeight": "1.0", "letterSpacing": "-0.12px", "fontWeight": "400"}],
        "display-md": ["34px", {"lineHeight": "1.47", "letterSpacing": "-0.374px", "fontWeight": "600"}],
        "dense-link": ["17px", {"lineHeight": "2.41", "letterSpacing": "0", "fontWeight": "400"}],
        "warm-display-xl": ["64px", {"lineHeight": "1.05", "letterSpacing": "-1.5px", "fontWeight": "400"}],
        "warm-display-lg": ["48px", {"lineHeight": "1.1", "letterSpacing": "-1px", "fontWeight": "400"}],
        "warm-display-md": ["36px", {"lineHeight": "1.15", "letterSpacing": "-0.5px", "fontWeight": "400"}],
        "warm-display-sm": ["28px", {"lineHeight": "1.2", "letterSpacing": "-0.3px", "fontWeight": "400"}],
        "warm-title-lg": ["22px", {"lineHeight": "1.3", "fontWeight": "500"}],
        "warm-title-md": ["18px", {"lineHeight": "1.4", "fontWeight": "500"}],
        "warm-title-sm": ["16px", {"lineHeight": "1.4", "fontWeight": "500"}],
        "warm-body-md": ["16px", {"lineHeight": "1.55", "fontWeight": "400"}],
        "warm-body-sm": ["14px", {"lineHeight": "1.55", "fontWeight": "400"}],
        "warm-caption": ["13px", {"lineHeight": "1.4", "fontWeight": "500"}],
        "warm-caption-upper": ["12px", {"lineHeight": "1.4", "fontWeight": "500", "letterSpacing": "1.5px"}]
      },
      animation: {
        'fade-in-up': 'fadeInUp 0.8s ease-out forwards',
        'breathe-glow': 'breatheGlow 10s ease-in-out infinite alternate',
        'meteor-effect': 'meteor 5s linear infinite',
        'shine': 'shine var(--duration) infinite linear',
        // Skeleton ustidan yuruvchi yorug'lik — `animate-pulse` dan ko'ra
        // sokinroq va "yuklanmoqda" hissini aniqroq beradi.
        'shimmer-sweep': 'shimmerSweep 1.8s cubic-bezier(0.4, 0, 0.2, 1) infinite',
        // Skeleton o'rnini haqiqiy tarkib egallaganda — sakrash o'rniga oqim.
        'content-in': 'contentIn 0.42s cubic-bezier(0.16, 1, 0.3, 1) both',
        // Fonda yangilanish chizig'i (yuqoridagi ingichka progress).
        'refresh-bar': 'refreshBar 1.15s cubic-bezier(0.65, 0, 0.35, 1) infinite',
      },
      keyframes: {
        fadeInUp: {
          '0%': { opacity: '0', transform: 'translateY(20px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        breatheGlow: {
          '0%': { opacity: '0.5', transform: 'scale(1)' },
          '100%': { opacity: '0.8', transform: 'scale(1.1)' },
        },
        floatUp: {
          '0%': { transform: 'translateY(0) scale(1)', opacity: '0' },
          '10%': { opacity: '0.8' },
          '100%': { transform: 'translateY(-400px) scale(0)', opacity: '0' },
        },
        meteor: {
          '0%': { transform: 'rotate(215deg) translateX(0)', opacity: '1' },
          '70%': { opacity: '1' },
          '100%': { transform: 'rotate(215deg) translateX(-500px)', opacity: '0' },
        },
        shine: {
          '0%': { 'background-position': '0% 0%' },
          '50%': { 'background-position': '100% 100%' },
          'to': { 'background-position': '0% 0%' },
        },
        shimmerSweep: {
          '0%': { transform: 'translateX(-110%)' },
          '100%': { transform: 'translateX(210%)' },
        },
        contentIn: {
          '0%': { opacity: '0', transform: 'translateY(6px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        refreshBar: {
          '0%': { transform: 'translateX(-100%) scaleX(0.35)' },
          '55%': { transform: 'translateX(30%) scaleX(0.75)' },
          '100%': { transform: 'translateX(190%) scaleX(0.35)' },
        },
      }
    },
  },
  plugins: [],
}